export const environment = {
  production: false,
  configname: 'iis-test',
  SERVER_URL: 'http://iis-test.posam.sk',
  PATH_UCHADZACI: '/test/iis/hr/ciselnik_test.nsf',
  REST_CURRENT_USER: '/test/iis/appl/oznamy_test.nsf/rest_user.xsp',
  REST_UCHADZACI: '/test/iis/hr/Ciselnik_test.nsf/rest_uchadzaci.xsp',
  REST_OZNAMY: '/test/iis/appl/oznamy_test.nsf/rest_oznamy.xsp',
  REST_OZNAMY_BY_CATEGORY: '/test/iis/appl/oznamy_test.nsf/rest_oznamy_kat.xsp',
  REST_OZNAM: '/test/iis/appl/oznamy_test.nsf/rest_oznamy.xsp',
  REST_CREATE_ID: '/test/iis/appl/oznamy_test.nsf/rest_create_id.xsp',
  REST_SET_OZNAM: '/test/iis/appl/oznamy_test.nsf/rest_create_oznam.xsp',
  REST_GET_VOTING: '/test/iis/appl/oznamy_test.nsf/rest_voting.xsp',
  REST_SET_VOTING: '/test/iis/appl/oznamy_test.nsf/rest_create_voting.xsp',
  REST_RYCHLY_OZNAM: '/test/iis/appl/oznamy_test.nsf/rest_rychly_oznam.xsp',
  REST_RYCHLA_OTAZKA: '/test/iis/appl/oznamy_test.nsf/rest_rychla_otazka.xsp',
  REST_UDALOSTI: '/test/iis/appl/oznamy_test.nsf/rest_udalosti.xsp',
  REST_EMOTIKON: '/test/iis/appl/oznamy_test.nsf/rest_emotikon.xsp',
  SET_EMOTIKON: '/test/iis/appl/oznamy_test.nsf/rest_create_emotikon.xsp',
  SET_ODPOVED: '/test/iis/appl/oznamy_test.nsf/rest_create_odpoved.xsp',
  REST_APLIKACIE: './assets/data/application-links-test.json',
  REST_IMAGE_UPLOAD: '/test/iis/appl/oznamy_test.nsf/rest_upload.xsp',
  REST_FORUM_LIST: '/test/iis/appl/oznamy_test.nsf/rest_prispevky.xsp',
  SET_FORUM_ITEM: '/test/iis/appl/oznamy_test.nsf/rest_create_prispevok.xsp',
  REST_FORUM_SUMAR: '/test/iis/appl/oznamy_test.nsf/rest_prispevky_prehlad.xsp',
  REST_OZNAMY_CATEGORIES: '/test/iis/appl/oznamy_test.nsf/rest_oznamy_categories.xsp',
  REST_GOLEM: '/test/iis/appl/oznamy_test.nsf/rest_org.xsp',
  REST_PODAKOVANIA: '/test/iis/appl/oznamy_test.nsf/rest_podakovania.xsp',
  REST_SET_PODAKOVANIE: '/test/iis/appl/oznamy_test.nsf/rest_create_thanks.xsp',
  REST_PODAKOVANIE_REMOVE: '/test/iis/appl/oznamy_test.nsf/rest_remove_thanks.xsp',
  REST_SET_QUESTION_HR: '/test/iis/appl/oznamy_test.nsf/rest_create_question_hr.xsp',

  REST_RP_GET_FAQ_LIST: '/test/iis/hr/poukazy_test.nsf/rest.xsp/getFAQ',
  REST_RP_SET_FAQ_QUESTION: '/test/iis/hr/poukazy_test.nsf/rest_create_faq.xsp',
  REST_RP_GET_REQUEST_LIST: '/test/iis/hr/poukazy_test.nsf/rest.xsp/getallrequests',
  REST_RP_GET_REQUEST_LIST_BY_STATUS: '/test/iis/hr/poukazy_test.nsf/rest_requests_kat.xsp',
  REST_RP_GET_REQUEST_LIST_BY_USER: '/test/iis/hr/poukazy_test.nsf/rest.xsp/getrequests',
  REST_RP_GET_REQUEST: '/test/iis/hr/poukazy_test.nsf/rest_request.xsp',
  REST_RP_GET_TEMPLATE_URL: '/test/iis/hr/poukazy_test.nsf/rest_template_url.xsp',
  REST_RP_SET_REQUEST: '/test/iis/hr/poukazy_test.nsf/rest_create_request.xsp',
  REST_RP_GET_CONTRIBUTION: '/test/iis/hr/poukazy_test.nsf/rest_contribution.xsp',
  REST_RP_CREATE_ID: '/test/iis/hr/poukazy_test.nsf/rest_create_id.xsp',
  REST_RP_GET_WFFN_ACTIONS: '/test/iis/hr/poukazy_test.nsf/rest_wffn.xsp',
  REST_RP_IMAGE_UPLOAD: '/test/iis/hr/poukazy_test.nsf/rest_upload.xsp',
  
  REST_ROR_GET_RATINGS: '/test/iis/hr/ror.nsf/rest.xsp/getROR',
  REST_ROR_GET_COMPETENCES: './assets/mockup/pozicie-a-kompetencie.json',
  REST_ROR_GET_RATING: '/test/iis/hr/ror.nsf/rest_ror.xsp',
  REST_ROR_SET_RATING: '/test/iis/hr/ror.nsf/rest_create_ror.xsp',
  REST_ROR_CREATE_ID: '/test/iis/hr/ror.nsf/rest_create_id.xsp',
  REST_ROR_GET_WFFN_ACTIONS: '/test/iis/hr/ror.nsf/rest_wffn.xsp',
  
  REST_CP_GET_RATINGS: './assets/mockup/cp-rating-list.json',
  REST_CP_GET_RATING: './assets/mockup/cp-rating.json',
  REST_CP_SET_RATING: '',
  REST_CP_CREATE_ID: './assets/mockup/rating-id.json',
  REST_CP_GET_THEMES: './assets/mockup/cp-otazky.json',
  REST_CP_GET_WFFN_ACTIONS: '.assets/mockup/rating-wffn-actions.json',

  REST_CODE_REVIEW_GET_RATINGS: './assets/mockup/code-review-list.json',
  REST_CODE_REVIEW_GET_RATING: './assets/mockup/code-review.json',
  REST_CODE_REVIEW_SET_RATING: '',
  REST_CODE_REVIEW_CREATE: '',
  REST_CODE_REVIEW_GET_THEMES: './assets/mockup/code-review-otazky.json',
  REST_CODE_REVIEW_GET_FUNCTIONAL_UNIT_LIST: './assets/mockup/functional-unit-list.json',
  REST_CODE_REVIEW_GET_WFFN_ACTIONS: './assets/mockup/code-review-wffn-actions.json',

  REST_PROJECT_GET_REPORT: './assets/mockup/project-report.json',
};
