
const api = {
    REST_LOGGED_USER: '/iis/appl/oznamy.nsf/rest_user.xsp',
    REST_POZA_USRS: '/iis/hr/ciselnik.nsf/rest_pouzivatelia.xsp',
    REST_POZA_USRGRPS: '/iis/hr/ciselnik.nsf/rest_skupiny.xsp',
    REST_POZA_EMPALL: '/iis/hr/ciselnik.nsf/rest_zamestnanci_vsetci.xsp',
    REST_POZA_EMPMY: '/iis/hr/ciselnik.nsf/rest_zamestnanci_moji.xsp',
    REST_POZA_EMPFAV: '/iis/hr/ciselnik.nsf/rest_zamestnanci_oblubeni.xsp',
    REST_POZA_EMPFADD: '/iis/hr/ciselnik.nsf/rest_pridaj_oblubeneho.xsp',
    REST_POZA_EMPFDEL: '/iis/hr/ciselnik.nsf/rest_odober_oblubeneho.xsp',
    REST_POZA_PERSDATA: '/iis/hr/ciselnik.nsf/rest_zamestnanec.xsp',
    REST_POZA_UPDPERSDATA: '/iis/hr/ciselnik.nsf/rest_nastav_zamestnanca.xsp',
    REST_POZA_UPDPERSDOC: '/iis/hr/ciselnik.nsf/rest_zamestnanec_uloz_prilohu.xsp',
    REST_POZA_DELPERSDOC: '/iis/hr/ciselnik.nsf/rest_zamestnanec_zmaz_prilohu.xsp',
    REST_POZA_PROFCOMPS: '/emp/profcomps',
    REST_POZA_PERSCOMPS: '/emp/perscomps',
    REST_POZA_COURSES: '/iis/hr/ciselnik.nsf/rest_skolenia.xsp',
    REST_POZA_COURSE: '/iis/hr/ciselnik.nsf/rest_skolenie.xsp',
    REST_POZA_CERTIFICATES: '/iis/hr/ciselnik.nsf/rest_certifikaty.xsp',
    REST_POZA_CERTIFICATE: '/iis/hr/ciselnik.nsf/rest_certifikat.xsp',
    REST_POZA_TARGETS: '/iis/hr/ror.nsf/rest_rors_goals.xsp',
    REST_POZA_PROJECTS: '/emp/projects',
    REST_POZA_PROJECT: '/emp/project',
    REST_POZA_UPDPROJECT: '/emp/project',
    REST_POZA_PROMEMBERS: '/emp/members',
    REST_POZA_UPDPROMEMBERS: '/emp/updmembers',
    REST_POZA_NEWMEETING: '/iis/hr/ror.nsf/rest_create_id.xsp',
    REST_POZA_MEETINGS: '/iis/hr/ror.nsf/rest_teamleader_meetings.xsp',
    REST_POZA_MEETING: '/iis/hr/ror.nsf/rest_load_teamleader_meeting.xsp',
    REST_POZA_UPDMEETING: '/iis/hr/ror.nsf/rest_save_teamleader_meeting.xsp',
    REST_POZA_NEWREVIEW: '/iis/hr/ror.nsf/rest_create_id.xsp',
    REST_POZA_REVIEWS: '/iis/hr/ror.nsf/rest_code_reviews.xsp',
    REST_POZA_REVIEW: '/iis/hr/ror.nsf/rest_load_code_review.xsp',
    REST_POZA_UPDREVIEW: '/iis/hr/ror.nsf/rest_save_code_review.xsp', 
    REST_POZA_NEWCLOSEOUT: '/iis/hr/ror.nsf/rest_create_id.xsp',
    REST_POZA_CLOSEOUTS: '/iis/hr/ror.nsf/rest_close_outs.xsp',
    REST_POZA_CLOSEOUT: '/iis/hr/ror.nsf/rest_load_close_out.xsp',
    REST_POZA_UPDCLOSEOUT: '/iis/hr/ror.nsf/rest_save_close_out.xsp',
    REST_POZA_NEWROR: '/iis/hr/ror.nsf/rest_create_ror_id.xsp',
    REST_POZA_RORS: '/iis/hr/ror.nsf/rest_close_outs.xsp',
    REST_POZA_ROR: '/iis/hr/ror.nsf/rest_load_ror.xsp',
    REST_POZA_UPDROR: '/iis/hr/ror.nsf/rest_save_ror.xsp',
    REST_POZA_THEMES: '/iis/hr/ciselnik.nsf/rest_temy.xsp',
    REST_POZA_SETTHEME: '/iis/hr/ciselnik.nsf/rest_nastav_temy.xsp',
    REST_POZA_TLCARDS: '/iis/hr/ror.nsf/rest_karta_teamlidra.xsp',
    REST_POZA_PROEVALS: '/emp/proevals',
    REST_POZA_NEWPROEVAL: '/emp/newproeval',
    REST_POZA_PROEVAL: '/emp/proeval',
    REST_POZA_UPDPROEVALUATION: '/emp/saveevaluation',

}
module.exports.api = api;

module.exports.config = {
    clientUrl: 'http://localhost:4200',
    serverUrl: 'http://dev9ba01.posam.sk',
    proxyPort: 3000,
    mockPort: 3001,
    mockGate: {
        [api.REST_LOGGED_USER]: false,
        [api.REST_POZA_USRS]: false,
        [api.REST_POZA_USRGRPS]: false,
        // [api.REST_POZA_EMPALL]: true,
        // [api.REST_POZA_EMPMY]: true,
        // [api.REST_POZA_EMPFAV]: true,
        // [api.REST_POZA_EMPFADD]: true,
        // [api.REST_POZA_EMPFDEL]: true,
        // [api.REST_POZA_PERSDATA]: true,
        // [api.REST_POZA_UPDPERSDATA]: true,
        // [api.REST_POZA_UPDPERSDOC]: true,
        // [api.REST_POZA_DELPERSDOC]: true,
        // [api.REST_POZA_PROFCOMPS]: false,
        // [api.REST_POZA_PERSCOMPS]: false,
        // [api.REST_POZA_COURSES]: true,
        // [api.REST_POZA_COURSE]: true,
        // [api.REST_POZA_CERTIFICATES]: true,
        // [api.REST_POZA_CERTIFICATE]: true,
        // [api.REST_POZA_NEWMEETING]: true,
        // [api.REST_POZA_MEETINGS]: true,
        // [api.REST_POZA_MEETING]: true,
        // [api.REST_POZA_UPDMEETING]: true,
        // [api.REST_POZA_NEWREVIEW]: true,
        // [api.REST_POZA_REVIEWS]: true,
        // [api.REST_POZA_REVIEW]: true,
        // [api.REST_POZA_UPDREVIEW]: true,
        // [api.REST_POZA_NEWCLOSEOUT]: true,
        // [api.REST_POZA_CLOSEOUTS]: true,
        // [api.REST_POZA_CLOSEOUT]: true,
        // [api.REST_POZA_UPDCLOSEOUT]: true,
        // [api.REST_POZA_NEWROR]: true,
        // [api.REST_POZA_RORS]: true,
        // [api.REST_POZA_ROR]: true,
        // [api.REST_POZA_UPDROR]: true,
        // [api.REST_POZA_TARGETS]: true,
        // [api.REST_POZA_THEMES]: true,
        // [api.REST_POZA_SETTHEME]: true,
        // [api.REST_POZA_TLCARDS]: true,
        // [api.REST_POZA_PROJECTS]: false,
        // [api.REST_POZA_PROJECT]: false,
        // [api.REST_POZA_UPDPROJECT]: false,
        // [api.REST_POZA_PROMEMBERS]: false,
        // [api.REST_POZA_UPDPROMEMBERS]: false,
        // [api.REST_POZA_PROEVALS]: false,
        // [api.REST_POZA_NEWPROEVAL]: false,
        // [api.REST_POZA_PROEVAL]: false,
        // [api.REST_POZA_UPDPROEVALUATION]: false,
   },
}

