export const HolidayVoucherConstants = {
    
    MIN_NIGHTS: 2,
    MIN_CONTRIBUTION_AMOUNT: 0,
    MAX_CONTRIBUTION_PERCENT: 0.55,
    LIST_VOUCHER_REQUEST_COUNT: 99,
    LIST_VOUCHER_FAQ_COUNT: 99,
    DEFAULT_STATUS_VOUCHER_REQUEST: 'DRAFT',

}